service: serverless-stress-vanilla

plugins:
  - serverless-stack-output

provider:
  name: aws
  runtime: nodejs12.x 
  stage: stress
  tracing:
    apiGateway: true
    lambda: true
  region: us-east-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'logs:CreateLogStream'
        - 'logs:PutLogEvents'
      Resource:
        - 'arn:aws:logs:*:*:log-group:/aws/lambda-insights:*'
    - Effect: 'Allow'
      Action:
        - 'xray:PutTraceSegments'
        - 'xray:PutTelemetryRecords'
      Resource:
        - '*'

functions:
  vanillaHelloWorld:
    handler: handler.handler
    layers:
      - arn:aws:lambda:us-east-1:580247275435:layer:LambdaInsightsExtension:12
    events:
      - http:
          path: vanilla
          method: get

custom:
  output:
    handler: output.handler
    file: .tmp/output.json